tailwind.config = {
    darkMode: "class",
    theme: {
      extend: {
        colors: {
          "on-primary": "#003824",
          "on-secondary-container": "#91c4a8",
          "tertiary": "#ffb3af",
          "surface-dim": "#101419",
          "on-tertiary-fixed": "#410005",
          "on-surface-variant": "#bbcabf",
          "on-tertiary-fixed-variant": "#842225",
          "primary-fixed": "#6ffbbe",
          "background": "#0a0e13",
          "outline": "#86948a",
          "surface-bright": "#36393f",
          "surface-container": "#1c2025",
          "surface": "#101419",
          "tertiary-fixed-dim": "#ffb3af",
          "error": "#ffb4ab",
          "on-tertiary-container": "#711419",
          "on-tertiary": "#650911",
          "error-container": "#93000a",
          "inverse-on-surface": "#2d3136",
          "on-background": "#e0e2ea",
          "surface-container-low": "#181c21",
          "tertiary-container": "#fc7c78",
          "surface-container-highest": "#31353b",
          "surface-container-lowest": "#0a0e13",
          "primary-fixed-dim": "#4edea3",
          "secondary-fixed-dim": "#9ed2b5",
          "inverse-primary": "#006c49",
          "primary-container": "#10b981",
          "surface-container-high": "#262a30",
          "on-primary-fixed": "#002113",
          "primary": "#4edea3",
          "on-error-container": "#ffdad6",
          "tertiary-fixed": "#ffdad7",
          "outline-variant": "#3c4a42",
          "on-error": "#690005",
          "on-surface": "#e0e2ea",
          "on-secondary-fixed-variant": "#1e4f3a",
          "secondary": "#9ed2b5",
          "on-primary-container": "#00422b",
          "surface-tint": "#4edea3",
          "on-secondary": "#013824",
          "secondary-container": "#21523c",
          "surface-variant": "#31353b",
          "on-secondary-fixed": "#002113",
          "inverse-surface": "#e0e2ea",
          "on-primary-fixed-variant": "#005236",
          "secondary-fixed": "#baeed1"
        },
        fontFamily: {
          "headline": ["Inter", "sans-serif"],
          "body": ["Inter", "sans-serif"],
          "label": ["Space Grotesk", "monospace"]
        },
        borderRadius: {"DEFAULT": "0px", "lg": "0px", "xl": "0px", "full": "9999px"},
      },
    },
}
